"""Hypothetical Document Embeddings (HyDE).

Hypothesis: Embedding a hypothetical answer (generated by the LLM)
produces a better retrieval vector than embedding the raw query.
The query "What temperature does water boil at?" is far from
document embeddings, but a hypothetical answer "Water boils at
100°C at standard atmospheric pressure" is close to the actual
documents containing this fact.

This bridges the query-document embedding gap by matching
document-like representations against documents.

References:
  - Gao et al. (2023): "Precise Zero-Shot Dense Retrieval without
    Relevance Labels" (HyDE)
  - HyPE (inverse HyDE): generate hypothetical questions per chunk
"""

import numpy as np
import requests

from ..base import Hypothesis, HypothesisResult
from ...backends.base import Backend, RetrievalResult


class HyDEHypothesis(Hypothesis):
    """Generate a hypothetical document, embed it, retrieve against that.

    Note: This hypothesis needs access to the backend (for re-retrieval)
    and Ollama (for hypothetical generation). It wraps around the standard
    retrieval pipeline rather than just reranking.
    """

    def __init__(
        self,
        ollama_url: str = "http://localhost:11434",
        chat_model: str = "qwen3.5:122b",
        backend: Backend | None = None,
        top_k: int = 10,
    ):
        self._ollama_url = ollama_url
        self._chat_model = chat_model
        self._backend = backend
        self._top_k = top_k

    @property
    def name(self) -> str:
        return "hyde"

    @property
    def description(self) -> str:
        return (
            "Hypothetical Document Embeddings — generate a hypothetical answer, "
            "embed it, and retrieve against that instead of the raw query"
        )

    def apply(
        self,
        query: str,
        results: list[RetrievalResult],
        embeddings: np.ndarray | None,
        query_embedding: np.ndarray | None,
    ) -> HypothesisResult:
        # Generate hypothetical document
        hyp_doc = self._generate_hypothetical(query)

        if not hyp_doc or self._backend is None:
            # Fall back to original results if generation fails
            return HypothesisResult(
                results=results,
                context_prompt=self._format(results),
                metadata={"fallback": True, "reason": "no backend or generation failed"},
            )

        # Embed the hypothetical document
        hyp_embedding = self._backend.embed_query(hyp_doc)

        # Re-retrieve using hypothetical embedding
        # We use retrieve_with_embeddings to get the new results
        new_results = self._backend.retrieve(query, self._top_k)

        # Also retrieve using the hypothetical embedding if backend supports it
        hyp_results = self._backend.retrieve(hyp_doc, self._top_k)

        # Merge: interleave original query results and HyDE results
        merged = self._merge_results(results, hyp_results)

        return HypothesisResult(
            results=merged,
            context_prompt=self._format(merged),
            metadata={
                "hypothetical_document": hyp_doc,
                "original_count": len(results),
                "hyde_count": len(hyp_results),
                "merged_count": len(merged),
            },
        )

    def _generate_hypothetical(self, query: str) -> str:
        """Generate a hypothetical document that would answer the query."""
        prompt = (
            "Write a short paragraph (3-5 sentences) that would be the "
            "ideal document to answer this question. Write as if you are "
            "the document itself, not as an assistant. Do not include the "
            "question — just write the answer passage.\n\n"
            f"Question: {query}"
        )

        try:
            resp = requests.post(
                f"{self._ollama_url}/api/chat",
                json={
                    "model": self._chat_model,
                    "messages": [{"role": "user", "content": prompt}],
                    "stream": False,
                },
                timeout=60,
            )
            resp.raise_for_status()
            return resp.json()["message"]["content"].strip()
        except Exception:
            return ""

    def _merge_results(
        self,
        original: list[RetrievalResult],
        hyde: list[RetrievalResult],
    ) -> list[RetrievalResult]:
        """Merge original and HyDE results via reciprocal rank fusion."""
        score_map: dict[str, float] = {}
        result_map: dict[str, RetrievalResult] = {}
        k = 60  # RRF constant

        for rank, r in enumerate(original, 1):
            score_map[r.doc_id] = score_map.get(r.doc_id, 0) + 0.5 / (rank + k)
            result_map[r.doc_id] = r

        for rank, r in enumerate(hyde, 1):
            score_map[r.doc_id] = score_map.get(r.doc_id, 0) + 0.5 / (rank + k)
            if r.doc_id not in result_map:
                result_map[r.doc_id] = r

        sorted_ids = sorted(score_map, key=lambda x: score_map[x], reverse=True)
        return [
            RetrievalResult(
                doc_id=did,
                text=result_map[did].text,
                score=score_map[did],
                metadata=result_map[did].metadata,
            )
            for did in sorted_ids
        ]

    def _format(self, results: list[RetrievalResult]) -> str:
        lines = ["Retrieved context (HyDE-enhanced):"]
        for i, r in enumerate(results, 1):
            lines.append(f"\n[{i}] (score: {r.score:.3f})")
            lines.append(r.text)
        return "\n".join(lines)
